services:
  - type: web
    name: ucdksea-api
    env: node
    rootDir: backend
    buildCommand: "npm ci && npx prisma generate || true && npm run build"
    startCommand: "node dist/server.js"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: ADMIN_ACTION_BASE
        value: "https://api.ucdksea.com"
      - key: APP_BASE_URL
        value: "https://www.ucdksea.com"
      - key: APP_LOGIN_URL
        value: "https://www.ucdksea.com/login"
      - key: ALLOWED_ORIGINS
        value: "https://ucdksea.com,https://www.ucdksea.com"
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USER
        value: "bjiwon766@gmail.com"
      - key: FROM_EMAIL
        value: "UCD KSEA <bjiwon766@gmail.com>"
