services:
  - type: web
    name: ucdksea-backend
    env: node
    rootDir: backend
    region: oregon
    plan: starter
    buildCommand: "npm ci"
    startCommand: "npm start"
    healthCheckPath: "/healthz"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20"
